#
#                                 vmRT-Thread
#
# Copyright (c) 2022-2024, Shanghai Real-Thread Electronic Technology Co., Ltd.
# All right reserved.
#
# Republication, copying or redistribution of this source code by any means is
# expressly prohibited without a prior written permission.
#
FROM {{ BENCH_NAME }}:qemu



RUN sudo apt-get remove -y gcc-multilib

# Update dockpin-apt.lock
# https://github.com/Jille/dockpin
# go install github.com/Jille/dockpin@latest
# Host $ ~/go/bin/dockpin apt pin --base-image {{ BENCH_NAME }}:{{ BENCH_IMG_DISTRO }}

COPY dockpin-apt.lock /tmp
RUN sudo /usr/local/sbin/dockpin apt install -p /tmp/dockpin-apt.lock


ENV RUSTUP_HOME={{ RUSTUP_HOME }}
ENV CARGO_HOME={{ CARGO_HOME }}
ENV RUSTUP_DIST_SERVER={{ RUSTUP_DIST_SERVER }}
ENV RUSTUP_UPDATE_ROOT={{ RUSTUP_UPDATE_ROOT }}

RUN sudo mkdir -p {{ RUSTUP_HOME }} {{ CARGO_HOME }} && sudo chown -R {{ BENCH_IMG_GROUP }}:{{ BENCH_IMG_USER }} {{ RUSTUP_HOME }} {{ CARGO_HOME }}
RUN export RUSTUP_DIST_SERVER=https://mirrors.ustc.edu.cn/rust-static && \
	export RUSTUP_UPDATE_ROOT=https://mirrors.ustc.edu.cn/rust-static/rustup && \
	curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable --profile default --no-modify-path
COPY cargo.tmol {{ CARGO_HOME }}/config.tmol


RUN . {{ CARGO_HOME }}/env && \
	rustup install stable && \
	rustup default stable && \
	rustup update && \
	rustup target add riscv64gc-unknown-none-elf && \
	cargo install cargo-binutils && \
	rustup component add llvm-tools-preview && \
	rustup component add rust-src


RUN echo "export RUSTUP_DIST_SERVER={{ RUSTUP_DIST_SERVER }}" | sudo tee -a {{ CARGO_HOME }}/env && \
	echo "export RUSTUP_UPDATE_ROOT={{ RUSTUP_UPDATE_ROOT }}" | sudo tee -a {{ CARGO_HOME }}/env && \
	echo "export RUSTUP_HOME={{ RUSTUP_HOME }}" | sudo tee -a {{ CARGO_HOME }}/env && \
	echo "export CARGO_HOME={{ CARGO_HOME }}" | sudo tee -a {{ CARGO_HOME }}/env && \
	echo ". {{ CARGO_HOME }}/env" | sudo tee -a {{ BENCH_INITRC }}

RUN sudo chmod -R o+rw {{ RUSTUP_HOME }} {{ CARGO_HOME }}

