#                                 KyberBench
# Copyright (c) 2025-2026, Kyber Development Team, all right reserved.
#
#
FROM {{ BENCH_NAME }}:arm10




RUN cd /usr/local/ && \
	sudo wget {{ ARM_ELF_GCC_URL }} && \
	sudo tar xvf {{ ARM_ELF_GCC_PACKAGE_NAME }} && \
	sudo mv {{ ARM_ELF_GCC_DIRECTORY_NAME }} {{ ARM_ELF_GCC_INSTALLED_NAME }} && \
	sudo rm -rfv {{ ARM_ELF_GCC_PACKAGE_NAME }}

RUN cd /usr/local/ && \
	sudo wget {{ ARM_LINUX_GCC_URL }} && \
	sudo tar xvf {{ ARM_LINUX_GCC_PACKAGE_NAME }} && \
	sudo mv {{ ARM_LINUX_GCC_DIRECTORY_NAME }} {{ ARM_LINUX_GCC_INSTALLED_NAME }} && \
	sudo rm -rfv {{ ARM_LINUX_GCC_PACKAGE_NAME }}


# Update dockpin-apt.lock
# https://github.com/Jille/dockpin
# go install github.com/Jille/dockpin@latest
# Host $ ~/go/bin/dockpin apt pin --base-image {{ BENCH_NAME }}:{{ BENCH_IMG_DISTRO }}

COPY dockpin-apt.lock /tmp
RUN sudo /usr/local/sbin/dockpin apt install -p /tmp/dockpin-apt.lock


