#                                 KyberBench
# Copyright (c) 2025-2026, Kyber Development Team, all right reserved.
#
#
FROM {{ BENCH_NAME }}:qemu


# https://developer.arm.com/downloads/-/gnu-a


RUN cd /usr/local/ && \
	sudo wget {{ ARM_ELF_GCC_URL }} && \
	sudo tar xvf {{ ARM_ELF_GCC_PACKAGE_NAME }} && \
	sudo mv {{ ARM_ELF_GCC_DIRECTORY_NAME }} {{ ARM_ELF_GCC_INSTALLED_NAME }} && \
	sudo rm -rfv {{ ARM_ELF_GCC_PACKAGE_NAME }}

RUN cd /usr/local/ && \
	sudo wget {{ ARM_LINUX_GCC_URL }} && \
	sudo tar xvf {{ ARM_LINUX_GCC_PACKAGE_NAME }} && \
	sudo mv {{ ARM_LINUX_GCC_DIRECTORY_NAME }} {{ ARM_LINUX_GCC_INSTALLED_NAME }} && \
	sudo rm -rfv {{ ARM_LINUX_GCC_PACKAGE_NAME }}



RUN echo "export PATH=/usr/local/{{ ARM_ELF_GCC_INSTALLED_NAME }}/bin:\${PATH}" | sudo tee -a {{ BENCH_INITRC }}
RUN echo "export PATH=/usr/local/{{ ARM_LINUX_GCC_INSTALLED_NAME }}/bin:\${PATH}" | sudo tee -a {{ BENCH_INITRC }}

