#
#                                 vmRT-Thread
#
# Copyright (c) 2022-2024, Shanghai Real-Thread Electronic Technology Co., Ltd.
# All right reserved.
#
# Republication, copying or redistribution of this source code by any means is
# expressly prohibited without a prior written permission.
#
FROM {{ BENCH_NAME }}:arm15



ENV RUSTUP_HOME={{ RUSTUP_HOME }}
ENV CARGO_HOME={{ CARGO_HOME }}
ENV RUSTUP_DIST_SERVER={{ RUSTUP_DIST_SERVER }}
ENV RUSTUP_UPDATE_ROOT={{ RUSTUP_UPDATE_ROOT }}

RUN sudo mkdir -p {{ RUSTUP_HOME }} {{ CARGO_HOME }} && sudo chown -R {{ BENCH_IMG_GROUP }}:{{ BENCH_IMG_USER }} {{ RUSTUP_HOME }} {{ CARGO_HOME }}
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable --profile default --no-modify-path
COPY cargo.tmol {{ CARGO_HOME }}/config.tmol


RUN . {{ CARGO_HOME }}/env && \
	rustup install stable && \
	rustup default stable && \
	rustup update && \
	rustup target add x86_64-unknown-none && \
	rustup target add aarch64-unknown-none && \
	rustup target add riscv64gc-unknown-none-elf && \
	cargo install cargo-binutils && \
	rustup component add llvm-tools-preview && \
	rustup component add rust-src


RUN echo "export RUSTUP_DIST_SERVER={{ RUSTUP_DIST_SERVER }}" | sudo tee -a {{ CARGO_HOME }}/env && \
	echo "export RUSTUP_UPDATE_ROOT={{ RUSTUP_UPDATE_ROOT }}" | sudo tee -a {{ CARGO_HOME }}/env && \
	echo "export RUSTUP_HOME={{ RUSTUP_HOME }}" | sudo tee -a {{ CARGO_HOME }}/env && \
	echo "export CARGO_HOME={{ CARGO_HOME }}" | sudo tee -a {{ CARGO_HOME }}/env && \
	echo ". {{ CARGO_HOME }}/env" | sudo tee -a {{ BENCH_INITRC }}

