#                                 KyberBench
# Copyright (c) 2025-2026, Kyber Development Team, all right reserved.
#
FROM {{ BENCH_NAME }}:develop



RUN curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -


