#                                 KyberBench
# Copyright (c) 2025-2026, Kyber Development Team, all right reserved.
#
FROM {{ BENCH_NAME }}:python3



# Update dockpin-apt.lock
# https://github.com/Jille/dockpin
# go install github.com/Jille/dockpin@latest
# Host $ ~/go/bin/dockpin apt pin --base-image {{ BENCH_NAME }}:{{ BENCH_IMG_DISTRO }}

COPY dockpin-apt.lock /tmp
RUN sudo /usr/local/sbin/dockpin apt install -p /tmp/dockpin-apt.lock


# Install Python Packages
# pip-compile --allow-unsafe --strip-extras --generate-hashes requirements.in -o requirements.txt
COPY requirements.txt /tmp/
RUN sudo -H pip install --no-cache-dir --require-hashes --no-warn-script-location -r /tmp/requirements.txt && sudo rm -f /tmp/requirements.txt


# RUN sudo curl -L https://mirrors.tuna.tsinghua.edu.cn/git/git-repo -o /usr/bin/repo && sudo chmod a+x /usr/bin/repo
COPY repo /usr/bin/repo
RUN sudo chmod a+x /usr/bin/repo
RUN echo "export REPO_URL='https://github.com/KyberLab/git-repo.git'" | sudo tee -a {{ BENCH_INITRC }}

