#                                 KyberBench
# Copyright (c) 2025-2026, Kyber Development Team, all right reserved.
#
FROM {{ BENCH_NAME }}:nodejs-repo




# Update dockpin-apt.lock
# https://github.com/Jille/dockpin
# go install github.com/Jille/dockpin@latest
# Host $ ~/go/bin/dockpin apt pin --base-image {{ BENCH_NAME }}:{{ BENCH_IMG_DISTRO }}

COPY dockpin-apt.lock /tmp
RUN sudo /usr/local/sbin/dockpin apt install -p /tmp/dockpin-apt.lock


RUN sudo npm config -g set registry https://registry.npmmirror.com/
RUN echo "puppeteer-download-base-url=\"https://cdn.npmmirror.com/binaries/chrome-for-testing\"" | sudo tee -a /etc/npmrc


